In [4]:
%matplotlib inline
import sympy as sympy
import numpy as np
from scipy import *

In [80]:
A = np.matrix([[-2, 2, 2, -2, 0],[-2, 2, 2, -2, 0], [2,-2,-2,2,0], [0,0,0,0,2], [0,0,0,0,2]])
print(A)

[[-2  2  2 -2  0]
 [-2  2  2 -2  0]
 [ 2 -2 -2  2  0]
 [ 0  0  0  0  2]
 [ 0  0  0  0  2]]


In [81]:
# Problem 8a)
r = np.linalg.matrix_rank(A)
print("rank(A) = " + str(r))

rank(A) = 2


In [82]:
# Problem 8b)
u, s, v = np.linalg.svd(A,full_matrices=True)
print("SVD Shapes = ", u.shape, s.shape, v.shape)
print("U = ")
print(u)
print("S = ")
S = np.zeros((5,5))
S[:5,:5] = np.diag(s)
print(S.round(2))
print("V' = ")
print(v)

('SVD Shapes = ', (5, 5), (5,), (5, 5))
U = 
[[-0.57735027  0.          0.          0.57735027 -0.57735027]
 [-0.57735027  0.          0.          0.21132487  0.78867513]
 [ 0.57735027  0.          0.          0.78867513  0.21132487]
 [ 0.          0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.70710678  0.70710678  0.          0.        ]]
S = 
[[ 6.93  0.    0.    0.    0.  ]
 [ 0.    2.83  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]]
V' = 
[[ 0.5        -0.5        -0.5         0.5         0.        ]
 [ 0.          0.          0.          0.          1.        ]
 [ 0.         -0.57735027 -0.21132487 -0.78867513  0.        ]
 [ 0.         -0.57735027  0.78867513  0.21132487  0.        ]
 [-0.8660254  -0.28867513 -0.28867513  0.28867513  0.        ]]


In [83]:
# Problem 8b)
U = u.transpose()*u
print("Check U'U = I")
print(U.round(2))
V = v*v.transpose()
print("Check V'V = I")
print(V.round(2))
print("Reconstruct A = U*S*V'")
print(u*S*v)

Check U'U = I
[[ 1.  0.  0.  0. -0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [-0.  0.  0.  0.  1.]]
Check V'V = I
[[ 1.  0. -0.  0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [ 0.  0. -0.  1.  0.]
 [-0.  0. -0.  0.  1.]]
Reconstruct A = U*S*V'
[[-2.  2.  2. -2.  0.]
 [-2.  2.  2. -2.  0.]
 [ 2. -2. -2.  2.  0.]
 [ 0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  2.]]


In [90]:
M = sympy.Matrix([[-2, 2, 2, -2, 0],[-2, 2, 2, -2, 0], [2,-2,-2,2,0], [0,0,0,0,2], [0,0,0,0,2]])
M.rref()
#R = np.ptp(A,axis = 1)
#print("Range(A) = ")
#print(R)
#Rp = np.ptp(A.transpose(),axis = 1)
#print("Range(A') = ")
#print(Rp)

(Matrix([
 [1, -1, -1, 1, 0],
 [0,  0,  0, 0, 1],
 [0,  0,  0, 0, 0],
 [0,  0,  0, 0, 0],
 [0,  0,  0, 0, 0]]), [0, 4])

In [91]:
Mp = sympy.Matrix([[-2, 2, 2, -2, 0],[-2, 2, 2, -2, 0], [2,-2,-2,2,0], [0,0,0,0,2], [0,0,0,0,2]]).transpose()
Mp.rref()

(Matrix([
 [1, 1, -1, 0, 0],
 [0, 0,  0, 1, 1],
 [0, 0,  0, 0, 0],
 [0, 0,  0, 0, 0],
 [0, 0,  0, 0, 0]]), [0, 3])

In [123]:
#Problem 10
x = np.array([1, 2, 3, 7])
x.shape = (4,1)
print("X = ")
print(x)
p1 = np.array([1, 2, 3, 4])
p1.shape = (4, 1)
p2 = np.array([4, -2, -6, -7])
p2.shape = (4, 1)
p3 = np.array([3, 4, -2, 1])
p3.shape = (4, 1)
P = np.column_stack((p1, p2, p3))
print("P = ")
print(P)
a1 = 1
a2 = 1
a3 = 1
xs = a1*p1 + a2*p2 + a3*p3
print("X* = ")
print(xs)
xe = x - xs
print("Therefore, x_e = ")
print(xe)

X = 
[[1]
 [2]
 [3]
 [7]]
P = 
[[ 1  4  3]
 [ 2 -2  4]
 [ 3 -6 -2]
 [ 4 -7  1]]
X* = 
[[ 8]
 [ 4]
 [-5]
 [-2]]
Therefore, x_e = 
[[-7]
 [-2]
 [ 8]
 [ 9]]
